DJ64DEV_VERSION = master
DJ64DEV_SITE = https://github.com/stsp/dj64dev
DJ64DEV_SITE_METHOD = git
DJ64DEV_LICENSE = GPL-3.0+
DJ64DEV_LICENSE_FILES = LICENSE
DJ64DEV_INSTALL_STAGING = YES
DJ64DEV_AUTORECONF = YES
DJ64DEV_CONF_OPTS = --disable-ncurses
DJ64DEV_BIN_ARCH_EXCLUDE = /usr/i386-pc-dj64/lib/

DJ64DEV_DEPENDENCIES += thunk_gen ctags elfutils

$(eval $(autotools-package))
